name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Pre Build tree sitter
      run: ls && cd vendor/tree-sitter-kotlin && npm install && npx tree-sitter generate && cd ../..
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
